# Site settings
title: Venkatesh Thallam
header-img: img/home-bg.jpg
email: venkatesh@jobsplane.com
description: "I write about things related to technology, entrepreneurship and companies in general!"
baseurl: ""
url: "http://vthallam.com"
twitter_username: vthallam
github_username:  venkateshthallam
facebook_username:  vthallam

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
